### ISSUE TITLE
feat: 초기 메인 화면 레이아웃 구현

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#1]
## Desc
초기 메인 화면 레이아웃 구현

## Detail
- 좌측 프로필단
- 중앙 채팅방-게임방 리스트 탭
- 우측 친구목록+DM목록

## Todo
- [x] 메인페이지 라우팅
- [x] 메인 화면 컴포넌트 분리하여 레이아웃 구현
- [x] 채팅방/게임방 리스트 탭 레이아웃 구현
- [x] 프로필 레이아웃 구현
- [x] 친구목록 레이아웃 구현
- [x] DM목록 레이아웃 구현

## Etc
- TO DO 주석으로 추가 구현지점 체크해둘것
