### ISSUE TITLE
style: 전체 페이지 스타일 구현

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#10]
## Desc
전체 페이지 스타일 구현

## Todo
- [x] 컬러 스타일 테마⠀성
- [x] 폰트 스타일 테마 생성
- [x] 버튼 스타일 테마 생성
- [x] 리스트 탭바 분리
- [x] 리스트 탭바 스타일 구현
- [x] 메인 페이지 스타일 구현
- [x] 채팅방리스트 페이지 스타일 구현
- [x] 게임방리스트 페이지 스타일 구현
- [x] 채팅방 페이지 레이아웃 스타일 구현
- [x] 게임방 페이지 레이아웃 스타일 구현

## Etc
