### ISSUE TITLE
feat: gameRoomList 구현

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#100]
## Desc
gameRoomList 구현

## Detail
gameRoomList에 대한 소켓 이벤트 받아서 리스트 구현

## Todo
- [x] 소켓 이벤트 설정
- [x] 리스트 UI 구현
- [ ] 이벤트 데이터 연동 확인

## Etc
