### ISSUE TITLE
feat: 매치메이킹 등록 UI 구현

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#103]
## Desc
매치메이킹 등록 UI 구현

## Detail
- 매치메이킹 등록 시 띄우는 대기 모달 구현
- 필요한 기능 부분 TODO 주석 채우기

## Todo
- [ ] 대기 모달 UI 구현
- [ ] 메치메이킹 등록 버튼 클릭 시 연결
- [ ] `searchGame` 이벤트 핸들링 주석 추가

## Etc

**Comment by sumnii** [comment]
호쏭님께서 진행중인 작업물 있음!
