### ISSUE TITLE
feat: 프로필 업적/배지 추가 및 히스토리 업데이트

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#109]
## Desc
프로필 업적(achievement)/배지 추가 및 히스토리 업데이트

## Detail
- 프로필에 업적 추가
- 업적에 따른 배지 추가
- 히스토리 UI 및 데이터 업데이트

## Todo
- [x] 프로필 데이터 중 업적 UI 추가
- [x] 배지 이미지 요청 api 구현
- [x] 업적 조건에 따라 배지 노출 로직 구현
- [x] 히스토리 데이터 확인하기(현재 스코어 노출 안됨)
- [x] 배지 스타일 구현
- [x] 히스토리 스타일 정리

## Etc
