### ISSUE TITLE
feat: 게임방 내 플레이어/관전자 리스트 구현

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#113]
## Desc
게임방 내 플레이어/관전자 리스트 구현

## Detail
- 관전 이벤트 구현
- 게임방 내 플레이어 리스트 구현
- 게임방 내 관전자 리스트 구현

## Todo
- [x] 플레이어 리스트 소켓 이벤트 수신
- [x] 관전자 리스트 소켓 이벤트 수신 
- [x] 리스트 context로 전달
- [x] 관전 시 roomID로 방 연결
- [x] 관전 이벤트 전송 구현
- [x] 타입 파일 분리

## Etc
