### ISSUE TITLE
style: 스타일 전체 검토

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#119]
## Desc
스타일 전체 검토

## Detail
스타일 없는 부분 적용해주고,
사파리에서의 스타일 확인해서 수정하기

## Todo
- [ ] 기본 버튼인 부분 버튼 테마 적용
- [ ] 상단바에 호쏭님 그라데이션 컬러 적용
- [ ] 사파리에서 뭉개지는 스타일 찾아서 수정

## Etc
