### ISSUE TITLE
feat: url을 통한 방 접근 핸들링

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#122]
## Desc
url을 통한 방 접근 핸들링

## Detail
- 404에 걸리지 않는 url 직접 접근에 대한 핸들링
- 구독 결과의 error를 확인하여 이전 페이지로 리다이렉트 처리

## Todo
- [x] 채팅방 구독 결과 핸들링 함수 구현
- [x] 게임방 구독 결과 핸들링 함수 구현
- [ ] Auth 구독 결과 함수 주석 처리

## Etc
