### ISSUE TITLE
refact: esLint rule 추가

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#13]
## Desc
필요한 린트 룰 추가

## Detail
- `semi: true`로 수정
- Typescript 체크 룰 추가
- 중복 import 리팩토링

## Todo
- [ ] semi룰 true로 수정
- [ ] ts 문법 체크 에러 룰 추가
- [ ] import React 삭제
