### ISSUE TITLE
feat: 프로필 영역 완성 (api, 스타일)

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#18]
## Desc
- 프로필 영역 완성 (api, 스타일)

## Detail
- 프로필 영역 api 연동
- 프로필 스타일 구현
- 다른 유저일 때 넣을 버튼 구상/구현

## Todo
- [x] 리액트 쿼리 초기 세팅
- [x] 유저 프로필 호출 api 구현
- [x] 유저 쿼리 생성
- [x] 유저 쿼리 데이터로 렌더링

ㅡㅡㅡㅡ 다른 브랜치에서 다시 ㅡㅡㅡㅡ
- [ ] 프로필 스타일 구현
- [ ] 다른 유저일 때 넣을 버튼 구현

## Etc
- 나와 다른 유저를 구분하려면? -> username도 전역으로 사용 -> `context`
- 다른 유저일 때 넣을 버튼
  - 친구일 때 : 친구 추가 버튼 노출X or disabled
  - 다른 유저일 때 : 친구 추가 버튼
