### ISSUE TITLE
feat: 토큰, username 전역 구현

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#21]
## Desc
로그인할 때 받는 토큰, username 전역 구현

## Detail
전역 요소가 두가지뿐이므로 context로 관리

## Todo
- [x] username, token으로 `context` 생성
- [x] context provider 삽입
- [x] 로그인 시 username, token 받아서 `context` 초기화
- [x] axios 인스턴스 기본값 설정 (헤더에 토큰 삽입)
