### ISSUE TITLE
feat: 프로필 영역 완성 (api 업데이트, 스타일)

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#22]
## Desc
- 프로필 영역 완성 (api, 스타일)

## Detail
- 전역 username으로 프로필 렌더링 업데이트
- 타 프로필일 때 버튼 구현
- 프로필 스타일 구현

## Todo
- [x] 프로필에서 전역 username으로 쿼리 호출
- [x] 프로필 쿼리 데이터로 렌더링
- [x] 프로필 관계 확인하여 버튼 구현
- [x] 프로필 스타일 구현
- [x] 친구 리스트 더미 데이터 생성해서 버튼 렌더링 테스트

## Etc
- 본인 : 로그아웃 버튼 (임시)
- 친구일 때 : 친구 삭제 버튼
- 다른 유저일 때 : 친구 추가 버튼
