### ISSUE TITLE
fix: 회원가입/로그인 기능 관련 수정

### ISSUE THREAD

**Issue by hoseong511** [4transcendence2/frontend#27]
## Desc
- 회원가입/ 로그인 기능 관련 수정

## Detail
- 회원가입
  - 아이디 중복확인 버튼 클릭 -> '필수 입력 인자입니다' 문구 처리
  - 아이디 입력창 이벤트 발생 -> 중복확인 state 초기화
  - 다른 아이디 입력, 중복확인
- 로그인
  - 비밀번호 입력창 확인 필요
  

## Todo
- [ ] 회원가입 기능 수정
- [ ] 로그인 기능 수정
- [ ] 주석: 로그인 2차 인증

## Etc
- 회원가입
  https://github.com/4transcendence2/frontend/pull/24#discussion_r1158175475 
- 로그인
  <img width="348" alt="image" src="https://user-images.githubusercontent.com/62678380/230027652-34a10290-ac3e-48d7-a675-9d99e6db8834.png">
