### ISSUE TITLE
feat: 오른쪽 파트 페이지별 뷰 분리

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#3]
## Desc
오른쪽 파트 페이지별 뷰 분리

## Detail
- `/chat/{chatid}`에서 참여자 리스트
- `/game/{gameid}`에서 플레이어/관전자 리스트
- 그 외 모든 페이지 친구목록/DM목록

## Todo
- [x] state 고려하여 분기 나누기
- [x] 채팅방 컴포넌트 간단하게 구현
- [x] 게임 페이지 컴포넌트 간단하게 구현
