### ISSUE TITLE
fix: 새로고침 시 유저 정보 초기화 버그 픽스

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#32]
## Desc
새로고침 시 유저 정보 초기화

## Detail
- 기존 로그인 관련 유저 정보(username, token)를 `useContext`를 이용하여 전역 관리하였으나 새로고침 시 리렌더링 되며 데이터 초기화 됨
- 데이터가 초기화되며 로그아웃 처리됨
- 처리하는 김에 전역으로 관리할 소켓 파일 추가

## Todo
- [x] 유저 정보를 쿠키에 담아 보관해두고 로딩할것
- [x] `useReducer`를 삭제하고 로그인 여부만 `context`로 관리
- [x] `userAuth` 파일로 유저 정보 get/set 구현
- [ ] 소켓 파일 생성 get/set

## Etc
- 추후 토큰 만료시간에 따라 쿠키 삭제하는 로직 추가 필요할듯
