### ISSUE TITLE
feat: 채팅방 내의 유저 목록 업데이트

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#43]
## Desc
- 채팅방 페이지 내 오른쪽 파트에 소켓 이벤트 연동

## Detail
- 채팅방에 맞게 컴포넌트 형태 변경
- `RightSide`에 ban 리스트 추가
- 채팅방 참여중인 유저 목록 업데이트 이벤트 등록
- 방장과 admin 구별하여 노출
- 방장/admin에게만 `BanList` 노출

## Todo
- [x] "chat" 페이지에서의 유저리스트 형태 리팩토링 (ban 리스트 추가)
- [x] ~~채팅방 참여중인 유저 목록 업데이트 이벤트 등록~~ 호쏭님 구현
- [x] 오른쪽 컴포넌트에서 `roomId` 조회
- [x] `inPageOf` 대신 url에서 page 조회
- [x] 채팅방별 유저 목록 분리
- [x] 프로필 유저 context로 관리
- [x] 해당 유저 클릭 시 프로필 변경 핸들러 구현
- [x] 방장과 admin 구분하는 아이콘 삽입
- [x] 방장과 admin에게만 노출되는 `BanList` 구현
- [ ] 디렉토리명 간결화 (호쏭님 브랜치 머지 후 작업)

## Etc
- 해당 이벤트 결과 data로 login이 있던데, 유저 로그아웃 시에도 채팅방 내에 있는건가..?

**Comment by hoseong511** [comment]
` 채팅방 참여중인 유저 목록 업데이트 이벤트 등록` 저 이거 하는 중 입니다!
