### ISSUE TITLE
fix: react-query 쿼리 키 통일

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#48]
## Desc
프로필에 대한 쿼리 키 일부는 `profile`, 일부는 `user`로 되어 있음

## Todo
- [x] 프로필에 대한 리액트쿼리 키 통일
- [x] `gameHistory` 있는 경우 렌더링 조건 추가
- [x] 내 프로필 다른 방식으로 (status를 실시간으로 받으려면 리패칭이 필요하나, 내 프로필은 언제나 온라인인 경우이므로!)
- [x] login -> 온라인 / logout -> 오프라인 으로 변경

## Etc
login/logout 외의 다른 status가 있을까?
