### ISSUE TITLE
refact: 디렉토리 단위의 전체 리팩토링

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#54]
## Desc
디렉토리 단위의 전체 리팩토링

## Detail
- 중복되는 단어 삭제하고 디렉토리명 간결하게 수정
- 깊지 않은 불필요한 alias 삭제
- 굳이 안 묶어도 되는 디렉토리 해제

## Todo
- [x] 중복되는 단어 삭제
- [x] 불필요한 alias 삭제
- [x] 불필요한 디렉토리 삭제

## Etc
