### ISSUE TITLE
feat: 프로필 컴포넌트 리렌더링 구현

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#6]
## Desc
- 프로필 컴포넌트 리렌더링 구현

## Detail
- 유저 클릭 시 클릭한 해당 유저 프로필로 리렌더링 필요
- 유저가 본인/친구/친구아님 에 따라 다른 구성 필요

## Todo
- [x] 유저아이디가 필요한 곳에 임시 유저아이디 심기
- [x] 클릭 시 `setState`로 유저아이디 설정
- [x] 유저아이디에 따라 다른 렌더링 설정

## Etc
- 유저정보 요청 시에 친구인지 true/false로 파싱된 값을 받을 수 있나(백 단에서 처리 후 데이터 전송)
- 아니면 친구목록을 리스트로 받아 거기에 로그인한 유저가 있는지 프론트 단에서 확인?
