### ISSUE TITLE
feat: 유저 드롭다운 메뉴 기능 구현

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#66]
## Desc
유저 드롭다운 메뉴 기능 구현

## Detail
- 드롭다운 메뉴 위치 설정
- 클릭 이벤트 핸들링
- props에 따른 메뉴 아이템 구분
  - 메인/게임방 내: 프로필/DM 보내기/게임 신청
  - 채팅방 내
    - 유저: 프로필/DM 보내기/게임 신청
    - 방장: 프로필/DM 보내기/게임 신청/음소거/내보내기/입장 금지/부방장 지정
    - 부방장: 프로필/DM 보내기/게임 신청/음소거/내보내기/입장 금지
  - 게임방 내

## Todo
- [x] 드롭다운 메뉴 위치 설정
- [x] 클릭 이벤트 핸들링
- [x] 드롭다운 모달 형태로 변경
- [x] 모달 기본 기능(외부 클릭 닫기/커스텀 닫기 핸들링)을 위한 커스텀 훅 구현
- [x] 드롭다운 메뉴의 각 아이템 구분
- [x] 드롭 메뉴 아이템 프로필 핸들러 구현
- [x] 본인인 경우 케밥 메뉴 안 보이게
- [x] 로그인한 유저의 권한과 대상의 권한에 따라 아이템 노출 로직 변경

## Etc
