### ISSUE TITLE
style: UI/UX 스타일 보완

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#87]
## Desc
UI/UX 스타일 보완

## Detail
- 크롬vs사파리: 크롬과 비교하여 기능상 방해가 되거나 UI를 크게 해치는 수준만 수정
  - 상단 네비게이션 바
  - DM 인풋 사이즈
- UX 관점
  - 로딩이 긴 부분에 로딩중 표시

## Todo
- [x] 상단 네비게이션바 밑줄 스타일 수정
- [x] DM Input 사이즈 수정
- [x] 로딩중 원 스타일 코드 가져오기
- [x] 로딩중에 로딩원 삽입 (특히 dmList)
