### ISSUE TITLE
fix: kick/ban 발생 시 채팅방 리스트 업데이트 누락

### ISSUE THREAD

**Issue by sumnii** [4transcendence2/frontend#89]
## Desc
kick/ban 발생 시 채팅방 리스트 업데이트 누락

## Detail
[기대 로직: 상황을 보는 유저는 채팅방 리스트 페이지에 있다고 가정]
- kick/ban이 발생하여 채팅방 참여자 수 변화
- 본인이 kick/ban 당해 참여중 -> 참여 가능으로 채팅방 리스트 이동

[현재 로직]
- kick/ban 발생 시 채팅방 리스트 업데이트 되지 않음

## Todo
- [x] 채팅방 리스트 구독 여부 확인
- [ ] 구독 X -> 구독 해제된 이유 찾아서 에러 픽스
- [x] 구독 O -> 다른 이벤트 수신 확인
- [x] 다른 이벤트 수신 여부 확인하여 백엔드 측에 확인 요청

**Comment by sumnii** [comment]
백엔드 측에서 해결 완료
